services:
  - type: web
    name: pacaembu-prazos-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app_mobile.py
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
